LIB_TYPE    := shared
LIB         := lib$(PACKAGE)CAFAna
LIBCXXFILES := $(wildcard *.cxx)

include SoftRelTools/standard.mk
include SoftRelTools/arch_spec_root.mk
include SoftRelTools/arch_spec_cafanacore.mk
include SoftRelTools/arch_spec_eigen.mk
include SoftRelTools/arch_spec_stan.mk
